import Image from 'next/image'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <header>
          <div className='flex m-5 items-center'>
            <Image src='/logo.png' alt='Hack Book' width={50} height={50} />
            <div className='text-xl ml-1'>Hack Book</div>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
