version: "3.8"

services:
  api:
    container_name: gin_practice_project
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api/:/go/src
    networks:
      - surprise
    tty: true

  frontend:
    container_name: next_practice_project
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend/:/app
      # exclude node_modules from being mounted
      - /app/node_modules
    command: sh -c "yarn install && yarn dev"
    networks:
      - surprise

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./app/database/init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:5432
    networks:
      - surprise
    restart: always

volumes:
  db-store:

networks:
  surprise:
    name: surprise
